### ISSUE TITLE
[Feature Request] Firmware update

### ISSUE THREAD

**Issue by therealhalifax** [emericg/WatchFlower#58]
Will you add Firmware Update (and also downgrade) for the xiaomi plant sensors in the near future?

Otherwise I will still need the offcial App in parallel.

**Comment by emericg** [comment]
Hi, I'm sorry but no this is not something that can be done (safely).
The devices supported by this application have all been reverse engineered to some extent, but reverse engineering firmware update would be 1/ a lot of work, 2/ always risky for your devices. There will always be some important details about the procedure and its limitations known only by the manufacturer (and since, probably already forgotten) that would make this endeavor a risky business...
Also, I do not have access to any of the firmware files, update manifests or anything.
